lookup = {
	'orientation': 
		{
			'n/a'   : 0,
			'N'     : 1,
			'NE'    : 2,
			'E'     : 3,
			'SE'    : 4,
			'S'     : 5,
			'SW'    : 6,
			'W'     : 7,
			'NW'    : 8,
		},
	'alphanumeric':
		{
			'n/a' : 0,
			'A'   : 1,
			'B'   : 2,
			'C'   : 3,
			'D'   : 4,
			'E'   : 5,
			'F'   : 6,
			'G'   : 7,
			'H'   : 8,
			'I'   : 9,
			'J'   : 10,
			'K'   : 11,
			'L'   : 12,
			'M'   : 13,
			'N'   : 14,
			'O'   : 15,
			'P'   : 16,
			'Q'   : 17,
			'R'   : 18,
			'S'   : 19,
			'T'   : 20,
			'U'   : 21,
			'V'   : 22,
			'W'   : 23,
			'X'   : 24,
			'Y'   : 25,
			'Z'   : 26,
			'0'   : 27,
			'1'   : 28,
			'2'   : 29,
			'3'   : 30,
			'4'   : 31,
			'5'   : 32,
			'6'   : 33,
			'7'   : 34,
			'8'   : 35,
			'9'   : 36,
		},
	'alphanumeric_color':
		{
			'n/a'   : 0,
			'white' : 1,
			'black' : 2,
			'gray'  : 3,
			'red'   : 4,
			'blue'  : 5,
			'green' : 6,
			'yellow': 7,
			'purple': 8,
			'brown' : 9,
			'orange': 10,
		},								  
	'shape':
		{
			'n/a'          : 0,
			'circle'       : 1,
			'cross'        : 2,
			'heptagon'     : 3,
			'hexagon'      : 4,
			'octagon'      : 5,
			'pentagon'     : 6,
			'quartercircle': 7,
			'rectangle'    : 8,
			'semicircle'   : 9,
			'square'       : 10,
			'star'         : 11,
			'trapezoid'    : 12,
			'triangle'     : 13,
		},		  
	'background_color':
		{
			'n/a'   : 0,
			'white' : 1,
			'black' : 2,
			'gray'  : 3,
			'red'   : 4,
			'blue'  : 5,
			'green' : 6,
			'yellow': 7,
			'purple': 8,
			'brown' : 9,
			'orange': 10,
		}
}